apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xsjp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xsjp
    app.kubernetes.io/part-of: coolstore
  name: devfile-sample-xsjp
  namespace: gnunn-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xsjp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xsjp
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:221adf3d42839ac374e49033f143239c1f9dd9c57092d4dd7ec226de3c80dede
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
