apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xsjp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xsjp
    app.kubernetes.io/part-of: coolstore
  name: devfile-sample-xsjp
  namespace: gnunn-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-xsjp
status:
  loadBalancer: {}
