apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: gateway-vertx-msha
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gateway-vertx-msha
    app.kubernetes.io/part-of: coolstore
  name: gateway-vertx-msha
  namespace: gnunn-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: gateway-vertx-msha
    weight: 100
status: {}
